cla1 = cla_systems = {
    "Microwave Theory and Techniques, IEEE Transactions on",
    "IEEE Trans. Computers",
    "DAC",
    "IEEE Computer",
    "DATE",
    "ICCAD",
    "ICSE",
    "Microwave Symposium Digest, MTT-S International",
    "IEEE Software",
    "VLSI Design",
    "IEEE Trans. Parallel Distrib. Syst.",
    "IPDPS",
    "Circuits and Systems, 2003. ISCAS '03. Proceedings of the 2003 International Symposium on",
    "COMPSAC",
    "CCGRID",
    "Journal of Systems and Software",
    "ITC",
    "ISCA",
    "ICDCS Workshops",
    "APSEC",
    "IEEE Design & Test of Computers",
    "ISQED",
    "ICDCS",
    "SC",
    "ICPP",
    "VTS",
    "Microelectronics Journal",
    "Microwave Theory and Techniques, IRE Transactions on",
    "IEEE Internet Computing",
    "ACM Great Lakes Symposium on VLSI",
    "ISLPED",
    "Asian Test Symposium",
    "IEEE Security & Privacy",
    "Future Generation Comp. Syst.",
    "Computers, IEEE Transactions on",
    "ICWS",
    "ACM SIGSOFT Software Engineering Notes",
    "ASE",
    "J. Parallel Distrib. Comput.",
    "Operating Systems Review",
    "SIGMETRICS",
    "ICCD",
    "DSD",
    "PDCAT",
    "RTCSA",
    "IEEE Micro",
    "ICPADS",
    "IPPS",
    "PDP",
    "FCCM",
    "IEEE Trans. VLSI Syst.",
    "The Journal of Supercomputing",
    "Parallel Computing",
    "ICS",
    "HPDC",
    "International Conference on Computational Science",
    "ISPAN",
    "APSCC",
    "PRDC",
    "Perform. Eval.",
    "SNPD",
    "DSN",
    "FPGA",
    "IEEE SCC",
    "ACM Queue",
    "ISORC",
    "IT Professional",
    "MICRO",
    "Parallel and Distributed Processing Symposium, 2003. Proceedings. International",
    "ASAP",
    "ICPP Workshops",
    "AICCSA",
    "SIGMETRICS Performance Evaluation Review",
    "ECBS",
    "ISVLSI",
    "ACM Trans. Design Autom. Electr. Syst.",
    "Computing in Science and Engineering",
    "SRDS",
    "IEEE International Workshop on Rapid System Prototyping",
    "Parallel and Distributed Systems, IEEE Transactions on",
    "IEEE Distributed Systems Online",
    "SenSys",
    "CODES+ISSS",
    "LISA",
    "PARELEC",
    "SOSP",
    "ISPDC",
    "Cluster Computing",
    "GCC",
    "PPOPP",
    "IEEE Real-Time Systems Symposium",
    "Journal of Systems Architecture",
    "ACM SIGOPS European Workshop",
    "HPCC",
    "Circuits and Systems, 2002. APCCAS '02. 2002 Asia-Pacific Conference on",
    "e-Science",
    "CLUSTER",
    "POLICY",
    "ECRTS",
    "QEST",
    "Euro-Par",
    "Systems, Man, and Cybernetics, Part B: Cybernetics, IEEE Transactions on",
    "ASPLOS",
    "DS-RT",
    "IEEE Real Time Technology and Applications Symposium",
    "TRANSDUCERS, Solid-State Sensors, Actuators and Microsystems, 12th International Conference on, 2003",
    "Real-Time Systems",
    "CASES",
    "SERVICES I",
    "Conf. Computing Frontiers",
    "GRID",
    "NOSSDAV",
    "Simulation Conference Proceedings, 1994. Winter",
    "IEEE Symposium on Computer Arithmetic",
    "Fuzzy Systems, 2003. FUZZ '03. The 12th IEEE International Conference on",
    "HPCA",
    "International Journal of Parallel Programming",
    "IEEE PACT",
    "ICCS (1)",
    "ACM Trans. Comput. Syst.",
    "Concurrency and Computation: Practice and Experience",
    "FTDCS",
    "International Conference on Computational Science (3)",
    "Autonomous Agents and Multi-Agent Systems",
    "HPCS",
    "Micro, IEEE",
    "International Conference on Computational Science (4)",
    "EMSOFT",
    "ICCSA (3)",
    "Design Test of Computers, IEEE",
    "RTSS",
    "ACM Trans. Embedded Comput. Syst.",
    "IJHPCA",
    "ISSS",
    "SIGARCH Computer Architecture News",
    "CODES",
    "PADS",
    "CSE (4)",
    "International Conference on Computational Science (2)",
    "ICCS (2)",
    "IEEE Trans. on CAD of Integrated Circuits and Systems",
    "SNPD (3)",
    "SBAC-PAD",
    "ICPADS (1)",
    "International Conference on Computational Science (1)",
    "ICMENS",
    "ISPA",
    "Intelligent Transportation Systems, 2002. Proceedings. The IEEE 5th International Conference on",
    "ICA3PP",
    "Evolvable Hardware",
    "Middleware",
    "GPC",
    "VECPAR",
    "DEBS",
    "ICAC"
}
cla2 = {
    "Theor. Comput. Sci.",
    "Electr. Notes Theor. Comput. Sci.",
    "Discrete Applied Mathematics",
    "FOCS",
    "Inf. Process. Lett.",
    "STOC",
    "Fundam. Inform.",
    "J. ACM",
    "Eur. J. Comb.",
    "SODA",
    "SIAM J. Comput.",
    "J. Symb. Comput.",
    "Des. Codes Cryptography",
    "SIAM J. Discrete Math.",
    "SIGPLAN Notices",
    "J. Comput. Syst. Sci.",
    "POPL",
    "Symposium on Computational Geometry",
    "J. Comb. Theory, Ser. A",
    "ACM Trans. Math. Softw.",
    "ISMVL",
    "ACM Trans. Program. Lang. Syst.",
    "PODC",
    "Inf. Comput.",
    "LICS",
    "ISSAC",
    "Journal of Graph Theory",
    "Mathematical Structures in Computer Science",
    "ISAAC",
    "Data Compression Conference",
    "Comput. Geom.",
    "J. Complexity",
    "SPAA",
    "ICFP",
    "Discrete & Computational Geometry",
    "SYNASC",
    "Random Struct. Algorithms",
    "J. Autom. Reasoning",
    "COCOON",
    "IEEE Conference on Computational Complexity",
    "TIME",
    "J. Funct. Program.",
    "ICALP",
    "J. Heuristics",
    "ESA",
    "Algorithmica",
    "SIGACT News",
    "Journal of Logic, Language and Information",
    "TARK",
    "Biological Cybernetics",
    "J. Algorithms",
    "Nord. J. Comput.",
    "PPDP",
    "Formal Methods in System Design",
    "J. Log. Comput.",
    "COLT",
    "MFCS",
    "Distributed Computing",
    "Electronic Colloquium on Computational Complexity (ECCC)",
    "CP",
    "Control Theory and Applications, IEE Proceedings D",
    "ICLP",
    "CiE",
    "Theory Comput. Syst.",
    "Developments in Language Theory",
    "STACS",
    "J. Discrete Algorithms",
    "WINE",
    "ACM Trans. Comput. Log.",
    "Constraints",
    "PEPM",
    "CAV",
    "CONCUR",
    "TACAS",
    "Acta Cybern.",
    "Combinatorica",
    "IEEE Transactions on Information Theory",
    "Graph Drawing",
    "ACRI",
    "STTT",
    "Discrete Mathematics",
    "DCC",
    "J. Comb. Theory, Ser. B",
    "Combinatorics, Probability & Computing",
    "EUROCRYPT",
    "SOFSEM",
    "Mathematical Methods in Electromagnetic Theory, 2002. MMET '02. 2002 International Conference on",
    "Natural Computing",
    "ECSQARU",
    "Computational & Mathematical Organization Theory"
}
cla3={
    "Computer Communications",
    "Computer Networks",
    "Communications, IEEE Transactions on",
    "Information Theory, IEEE Transactions on",
    "Selected Areas in Communications, IEEE Journal on",
    "AINA",
    "GLOBECOM",
    "ICC",
    "LCN",
    "IWCMC",
    "INFOCOM",
    "ISCC",
    "Neural Networks, 1993. IJCNN '93-Nagoya. Proceedings of 1993 International Joint Conference on",
    "Communications, 2003. ICC '03. IEEE International Conference on",
    "IEEE/ACM Trans. Netw.",
    "Communications Magazine, IEEE",
    "AINA Workshops",
    "SIGCOMM",
    "Wireless Networks",
    "Vehicular Technology Conference, 2003. VTC 2003-Spring. The 57th IEEE Semiannual",
    "IEEE Transactions on Wireless Communications",
    "WCNC",
    "Vehicular Technology Conference, 2002. Proceedings. VTC 2002-Fall. 2002 IEEE 56th",
    "Computer Communication Review",
    "IEEE Trans. Mob. Comput.",
    "MONET",
    "Personal, Indoor and Mobile Radio Communications, 2002. The 13th IEEE International Symposium on",
    "IPSN",
    "Vehicular Technology, IEEE Transactions on",
    "PerCom Workshops",
    "SAINT Workshops",
    "Communication Technology Proceedings, 2003. ICCT 2003. International Conference on",
    "SAINT",
    "ICNS",
    "NCM",
    "PerCom",
    "Int. Journal of Network Management",
    "CNSR",
    "MSWiM",
    "Wireless Communications and Networking, 2003. WCNC 2003. 2003 IEEE",
    "WOWMOM",
    "ICNP",
    "Communications Letters, IEEE",
    "ICN",
    "J. Network and Computer Applications",
    "Networking",
    "AINA (2)",
    "Mobility Conference",
    "CoNEXT",
    "IJMC",
    "WiMob",
    "Ad Hoc Networks",
    "MobiHoc",
    "AINA (1)",
    "Mobile Computing and Communications Review",
    "Microwave and Telecommunication Technology, 2002. CriMiCo 2002. 12th International Conference",
    "Peer-to-Peer Computing",
    "Optical Communication, 1996. ECOC '96. 22nd European Conference on",
    "FGCN (2)",
    "Computers and Communication, 2003. (ISCC 2003). Proceedings. Eighth IEEE International Symposium on",
    "ICN/ICONS/MCL",
    "Broadcasting, IEEE Transactions on",
    "Networks",
    "AICT/ICIW",
    "ICUIMC",
    "FGCN (1)",
    "AICT",
    "MOBICOM",
    "MSN",
    "Wireless Communications and Mobile Computing",
    "J. Network Syst. Manage.",
    "ICOIN",
    "MoMM",
    "Spread Spectrum Techniques and Applications, 2002 IEEE Seventh International Symposium on",
    "NBiS",
    "APNOMS",
    "MobiQuitous",
    "Communications, IEE Proceedings-",
    "Africon Conference in Africa, 2002. IEEE AFRICON. 6th",
    "Network, IEEE",
    "AINA Workshops (2)",
    "AINA Workshops (1)",
    "IJNVO",
    "Microwave Symposium Digest, 1980 MTT-S International",
    "Microwave Symposium Digest, GMTT International",
    "NETGAMES",
    "Electronics Communication Engineering Journal",
    "Antennas and Propagation, IEEE Transactions on",
    "Photonics Technology Letters, IEEE",
    "Lightwave Technology, Journal of",
    "Microwave Symposium Digest, 2003 IEEE MTT-S International",
    "Antennas and Propagation Magazine, IEEE",
    "Microwaves, Antennas and Propagation, IEE Proceedings -",
    "MobiMedia"
}

cla4 = cla_graphics = {
    "ACM Multimedia",
    "ACM Trans. Graph.",
    "IEEE Trans. Vis. Comput. Graph.",
    "IV",
    "IEEE Computer Graphics and Applications",
    "IEEE Visualization",
    "SIGGRAPH",
    "IEEE MultiMedia",
    "SIBGRAPI",
    "ISM",
    "ICME",
    "VRST",
    "Computer-Aided Design",
    "CGIV",
    "The Visual Computer",
    "MUE",
    "Pacific Conference on Computer Graphics and Applications",
    "Computer Aided Geometric Design",
    "VR",
    "Computer Graphics and Applications, IEEE",
    "SIGGRAPH Posters",
    "3DPVT",
    "Computer Graphics International",
    "GRAPHITE",
    "MMM",
    "Graphics Interface",
    "SI3D",
    "ACIVS",
    "APGV",
    "INFOVIS",
    "VRCAI",
    "Symposium on Solid and Physical Modeling",
    "Shape Modeling International",
    "Web3D",
    "CDVE",
    "Computers & Graphics"
}
cla5 = cla_hci = {
    "HICSS",
    "CHI Extended Abstracts",
    "CHI",
    "IUI",
    "Advances in Computer Entertainment Technology",
    "SIGDOC",
    "Hypertext",
    "Mobile HCI",
    "CSCW",
    "AIED",
    "AVI",
    "ICMI",
    "Personal and Ubiquitous Computing",
    "WHC",
    "Presence",
    "ASSETS",
    "HRI",
    "IEEE Pervasive Computing",
    "OZCHI",
    "VL/HCC",
    "ISMAR",
    "NordiCHI",
    "UIST",
    "IVA",
    "NIME",
    "GROUP",
    "Tangible and Embedded Interaction",
    "Creativity & Cognition",
    "VL",
    "Int. Conf. Interaction Sciences",
    "Int. J. Hum.-Comput. Stud.",
    "Edutainment",
    "HCI (1)",
    "INTERACT (2)",
    "HCI (2)",
    "PETRA",
    "Computers in Entertainment",
    "HCI (4)",
    "HCI (9)",
    "ICCHP",
    "HCI (6)",
    "HCI (3)",
    "HCI (10)",
    "Interacting with Computers",
    "HCI (8)",
    "HCI (7)",
    "ETRA",
    "HCI (5)",
    "HCI (12)",
    "IJWBC",
    "Systems, Man and Cybernetics, Part A: Systems and Humans, IEEE Transactions on",
    "HCI (13)",
    "ACM Trans. Comput.-Hum. Interact.",
    "WMTE",
    "RoboCup",
    "INTERACT (1)",
    "C5",
    "ECSCW",
    "BCS HCI (2)",
    "Int. Sym. Wikis",
    "Conference on Designing Interactive Systems",
    "IDC"
}

cla6= cla_nlp = {
    "COLING",
    "ACL",
    "EACL",
    "EMNLP",
    "HLT-NAACL",
    "Computational Linguistics",
    "ANLP",
    "Speech Communication",
    "CICLing",
    "COLING-ACL",
    "TSD",
    "HLT"
}

cla7=cla_cv = {
    "IEEE Trans. Pattern Anal. Mach. Intell.",
    "Pattern Recognition Letters",
    "ICDAR",
    "Pattern Recognition",
    "ICIP",
    "ICCV",
    "Pattern Recognition, 2002. Proceedings. 16th International Conference on",
    "ICPR (3)",
    "ICPR (1)",
    "International Journal of Computer Vision",
    "Pattern Analysis and Machine Intelligence, IEEE Transactions on",
    "Image Vision Comput.",
    "ICPR (2)",
    "ICIAP",
    "Image Processing. 2002. Proceedings. 2002 International Conference on",
    "ICPR (4)",
    "MICCAI (1)",
    "Journal of Mathematical Imaging and Vision",
    "AVSS",
    "Computer Vision and Image Understanding",
    "SCIA",
    "CVPR",
    "ISBI",
    "DICTA",
    "CVPR (1)",
    "ISVC (2)",
    "CRV",
    "CIARP",
    "IEEE Transactions on Image Processing",
    "CVPR (2)",
    "Medical Imaging, IEEE Transactions on",
    "ISVC (1)",
    "CAIP",
    "Image Processing, IEEE Transactions on",
    "FG",
    "AIPR",
    "Mach. Vis. Appl.",
    "ICIP (1)",
    "MICCAI (2)",
    "J. Visual Communication and Image Representation",
    "MVHI",
    "ICIAR",
    "ICVS",
    "Computer Vision and Pattern Recognition, 2003. Proceedings. 2003 IEEE Computer Society Conference on",
    "Circuits and Systems for Video Technology, IEEE Transactions on",
    "ICIP (3)",
    "PReMI",
    "DAGM-Symposium",
    "IIH-MSP",
    "PSIVT",
    "Vision, Image and Signal Processing, IEE Proceedings -",
    "ICIG",
    "3DIM",
    "ACCV (2)",
    "WACV"
}

cla8=cla_db_ir = {
    "Inf. Sci.",
    "SIGIR",
    "IEEE Trans. Knowl. Data Eng.",
    "SIGMOD Conference",
    "CIKM",
    "WWW",
    "ICDE",
    "ICDM",
    "Web Intelligence",
    "DEXA Workshops",
    "VLDB",
    "JCDL",
    "KDD",
    "Decision Support Systems",
    "JASIST",
    "SIGMOD Record",
    "DEXA Workshop",
    "DG.O",
    "Data Knowl. Eng.",
    "Inf. Process. Manage.",
    "ACM Trans. Database Syst.",
    "ICDM Workshops",
    "SSDBM",
    "PODS",
    "WKDD",
    "Web Intelligence/IAT Workshops",
    "ICDE Workshops",
    "PAKDD",
    "IDEAS",
    "ICEBE",
    "Knowl.-Based Syst.",
    "DATA BASE",
    "PCM",
    "EDOC",
    "DASFAA",
    "GIS",
    "Knowledge and Data Engineering, IEEE Transactions on",
    "ACM Trans. Inf. Syst.",
    "AGILE",
    "CIVR",
    "ECIR",
    "ACM Symposium on Document Engineering",
    "Multimedia Information Retrieval",
    "ICWE",
    "ICIW",
    "ICSC",
    "VLDB J.",
    "Inf. Syst.",
    "WISE",
    "Information Systems Frontiers",
    "IDEAL",
    "Intell. Data Anal.",
    "ACM Conference on Electronic Commerce",
    "RSKT",
    "SIGKDD Explorations",
    "ICMB",
    "Mobile Data Management",
    "RSFDGrC",
    "J. Intell. Inf. Syst.",
    "Knowl. Inf. Syst.",
    "CLEF",
    "ISWC",
    "SKG",
    "ADMA",
    "iiWAS",
    "SIGIR Forum",
    "PVLDB",
    "HICSS (2)",
    "ESWC",
    "HICSS (4)",
    "ICEGOV",
    "HICSS (1)",
    "APWeb",
    "MDM",
    "GeoInformatica",
    "Data Min. Knowl. Discov.",
    "Inf. Retr.",
    "Information Systems Research",
    "K-CAP",
    "World Wide Web",
    "WWW (Special interest tracks and posters)",
    "CAiSE",
    "EDBT",
    "OTM Conferences (1)",
    "Advanced Engineering Informatics",
    "J. Information Science",
    "WWW (Alternate Track Papers & Posters)",
    "Telematics and Informatics",
    "MLDM",
    "ER",
    "APWeb/WAIM",
    "RecSys",
    "DEXA",
    "Distributed and Parallel Databases",
    "ECDL",
    "WETICE",
    "OTM Workshops",
    "HICSS (3)",
    "ICDS",
    "IJITM",
    "HICSS (5)"
}

total_len=len(cla1)+len(cla2)+len(cla3)+len(cla4)+len(cla5)+len(cla6)+len(cla7)+len(cla8)
print(total_len)
print(f"cla1={len(cla1)}")
print(f"cla2={len(cla2)}")
print(f"cla3={len(cla3)}")
print(f"cla4={len(cla4)}")
print(f"cla5={len(cla5)}")
print(f"cla6={len(cla6)}")
print(f"cla7={len(cla7)}")
print(f"cla8={len(cla8)}")
